services:
  db:
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_interval: 10s
      start_period: 40s
      timeout: 20s
      retries: 10
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql


  playgobackend:
    build: 
      context: .
      dockerfile: ./cmd/main/Dockerfile
    container_name: playgobackend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: user_password
      DB_NAME: dbname

volumes:
  mysql-data:
networks:
  default:
