services:
  db:
    image: postgres:latest
    platform: linux/amd64
    container_name: postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_NAME=postgres
    ports:
      - "5432:5432"  # Map host port 5432 to container port 5432
    networks:
      - play
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres || exit 1"]
      interval: 10s  # Check every 10 seconds
      timeout: 5s    # Timeout after 5 seconds
      retries: 3     # Mark as unhealthy after 3 failures
      start_period: 30s  # Wait 30 seconds before starting health checks


  playgobackend:
    build: 
      context: .
      dockerfile: ./cmd/main/Dockerfile
    container_name: playgobackend
    ports:
      - "8080:8080"
    networks:
      - play
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: "db:5432"
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: postgres
  
  migrate:
    build:
      context: .
      dockerfile: ./cmd/main/Dockerfile.migrate
    entrypoint: ["/bin/sh", "/migrations/entrypoint.sh"]
    environment:
      DATABASE_URL: postgres://postgres:postgres123@db:5432/postgres?sslmode=disable
    volumes:
      - ./db/migrations:/migrations
      - ../cmd/entrypoint.sh:/migrations/entrypoint.sh
    depends_on:
      db:
        condition: service_healthy



volumes:
  pgdata:
networks:
  play:
