services:
  db:
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_interval: 10s
      start_period: 40s
      timeout: 20s
      retries: 10
    image: postgres:latest
    platform: linux/amd64
    container_name: PostgresCont
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_NAME=postgres
    expose:
      - "5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data


  playgobackend:
    build: 
      context: .
      dockerfile: ./cmd/main/Dockerfile
    container_name: playgobackend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: user_password
      DB_NAME: dbname

volumes:
  postgres_db:
networks:
  default:
